server:
  host: localhost
  port: 9000
  contextPath: /v1

spring:
  application:
    name: springLearning
  profiles:
    active: development
  logging:
    file: logs/dev_app.log
    pattern:
      console: "%d %-5level %logger : %msg%n"
      file: "%d %-5level [%thread] %logger : %msg%n"
    level:
      ROOT: DEBUG
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring?autoReconnect=true&useSSL=false
    username: spring
    password: spring
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true